### ISSUE TITLE
   assert reference not in parent.children AssertionError

### ISSUE THREAD

**Issue by pxs7** [Nic30/pyDigitalWaveTools#14]
when run demo code as

#!/usr/bin/env python3
import json
import sys
from pyDigitalWaveTools.vcd.parser import VcdParser

fname=fsdbfile

with open(fname,"r") as vcd_file:
    vcd = VcdParser()
    vcd.parse(vcd_file)
    data = vcd.scope.toJson()
    print(json.dumps(data, indent=4, sort_keys=True))

the vcd file is generated from fsdb  by

fsdb2vcd test.fsdb -o test.vcd

**Comment by pxs7** [comment]
Traceback (most recent call last):        
  File "vcd_test.py", line 20, in <module>
    vcd.parse(vcd_file)
  File "pyDigitalWaveTools/vcd/parser.py", line 153, in parse    self.keyword_dispatch[token[1]](tokeniser, token[1])
  File "pyDigitalWaveTools/vcd/parser.py", line 246, in vcd_var
    assert reference not in parent.children
AssertionError
